on:
  pull_request:
  push:
    branches: [main]

jobs:
  action:
    runs-on: ubuntu-latest

    permissions:
      actions: read # Required to download repository artifact.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      pull-requests: write # Required to add PR comment and label.

    steps:
      - uses: RobinOlofsson/terraflow@main
