name: JS Actions

on:
  pull_request_review:
    types: [submitted]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ha-ha
        uses: ./.github/actions/consent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
